### ISSUE TITLE
Bots always on last position

### ISSUE THREAD

**Issue by matbrgz** [all-contributors/cli#166]
On contributor table bot must always be at last positions.

**Comment by Berkmann18** [comment]
Would that be for _all_ bots or just the All Contributors one?

**Comment by MatheusRV** [comment]
All bots i guess.

**Comment by Berkmann18** [comment]
I'm okay with this.
@all-contributors/core Thoughts?

**Comment by Berkmann18** [comment]
I'm okay with this.
@jakebolam @sinchang @tbenning Thoughts on that?

**Comment by jakebolam** [comment]
I'm open to it. 

@MatheusRV what's the motivation behind this?

**Comment by MatheusRV** [comment]
> I'm open to it.
> 
> @MatheusRV what's the motivation behind this?

Just cosmetic for valorizate user not bots.

**Comment by jakebolam** [comment]
Yep. I wonder how we will enforce this?

One of the benefits right now is we don't manage order, anyone can change the array how they want and the readme file will reflect this. Forcing bots to be last would break this behaviour. 

Some bots also don't report themselves as bots, and some usernames have the keyword 'bot' in it, how would we distinguish between these?

**Comment by Berkmann18** [comment]
@jakebolam Perhaps, having that as a *suggestion* instead of a rule so it keeps the order to whoever has control over it within a repo that uses AC.

> Some bots also don't report themselves as bots, and some usernames have the keyword 'bot' in it, how would we distinguish between these?

I was going to suggest, looking for an undefined/null profile URL but some bots do have one (e.g: `sentinel-bot`, `codacy-bot`).

**Comment by Berkmann18** [comment]
@MatheusRV Have you found any better ides?

**Comment by Berkmann18** [comment]
@matbrgz Have you tried any solutions for this?

**Comment by tenshiAMD** [comment]
Closing this for now. Please refer to [this one](https://github.com/all-contributors/cli/issues/320) instead. Thank you! 🎉
