### ISSUE TITLE
A way to link ideas to relevant issues

### ISSUE THREAD

**Issue by mrchief** [all-contributors/cli#175]
**Is your feature request related to a problem? Please describe.**
Currently, `ideas` do not link to anything

![image](https://user-images.githubusercontent.com/781818/54294952-81610a00-4588-11e9-99a8-ae6123a3e380.png)

**Describe the solution you'd like**
I think we can make them link to relevant `issues` by introducing a setting in `.all-contributorsrc`. It is common to have labels like `enhancement`, `feature` or similar in a github repo. For those who have setup such labels, the bot can link it up by using an URL like this:

`https://github.com/<org>/<repo>/issues?q=is%3Aopen+label%3Aenhancement+author%3A%22<author username>+%22`

I think something like this in `.all-contributorsrc`:

```
{
  labels: {
    ideas: "enhancement",
    design: "feature",
    ...
  }
}
```

**Describe alternatives you've considered**
I think `types` may be useful here and if so, it's not very evident from the docs.

E.g., I'm not sure if this is valid or how would I configure `url`, `description` etc; do I need to specify everything from scratch including `symbol`, `description` etc. or can I override just some parts and so on.

```
  "types": {
    "ideas": {
      "link": "[<%= symbol %>](<%= url %> \"<%= description %>\"),"
    }
  },
```

**Additional context**
This feature can also contribute towards [auto-discoverability](https://github.com/all-contributors/all-contributors-cli/issues/117) capability.

**Comment by Berkmann18** [comment]
That's an interesting and good idea which could help in associating contributions to categories (ie. auto-fetching) with not too much manual involvement.
For the links thing itself, I think having utilising the `types` field would be the way to go.

@jakebolam @sinchang Thoughts?

**Comment by jakebolam** [comment]
This sounds awesome. Thanks for the in-depth research @mrchief. Are you interested in implementing this?

**Comment by mrchief** [comment]
I'm already behind on my bot contributory PR, you sure you want me to sign up for this as well? :)

I'd love to once I clear my backlog though!

**Comment by Berkmann18** [comment]
@mrchief Did you get a chance to have a look at this since?

**Comment by tenshiAMD** [comment]
Related to https://github.com/all-contributors/cli/issues/88
