### ISSUE TITLE
read config from package.json - from `config.all-?contributors` field?

### ISSUE THREAD

**Issue by tunnckoCore** [all-contributors/cli#22]
Amazing idea, btw!

In help can be https://github.com/jonschlinkert/github-contributors

**Comment by kentcdodds** [comment]
I'm fine with it, but I wouldn't do it that way. I like to avoid bloating my package.json.

**Comment by jfmengels** [comment]
Hi @tunnckoCore!

This actually used to be the case. If I recall correctly, there used to be two files: one with the list of contributors, and one with the configuration, which could be replaced by putting it in the package.json.

I removed support for it at some point. Now there is one file for both the config and the list of contributors to keep stuff simple and co-located.

We could have the config in the package.json, but then you'd still have the `.all-contributorsrc` file for the list of contributors. I am not against adding support back for it, but I'm not sure that it's really all that useful. Do let us know if you have some good reasons why you prefer to use package.json or can't use the rc file :)

**Comment by tunnckoCore** [comment]
> I like to avoid bloating my package.json.

I like to avoid bloating the root. In anyway we have many tools that loads config from package.json, so it worth.

> If I recall correctly

Worth nothing to look on both places - package.json config, and `.all-contributorsrc` (damn, can't find them currently, but there's couple of packages that tries to load from `package.json`, `.NAMErc, `.NAMErc.json`, `.NAMErc.js`). List of contributors can be in the config too, or try from package.json's `contributors` field.

**Comment by Berkmann18** [comment]
@tunnckoCore 
> Worth nothing to look on both places - package.json config, and .all-contributorsrc (damn, can't find them currently, but there's couple of packages that tries to load from package.json, .NAMErc,.NAMErc.json,.NAMErc.js). List of contributors can be in the config too, or try from package.json'scontributors` field.

Have you found said package(s) that would handle that?

**Comment by tunnckoCore** [comment]
Mmm don't know for what I was talking about but probably `cosmiconfig` and [@tunnckocore/pretty-config](https://npmjs.com/package/@tunnckocore/pretty-config) would work?

**Comment by Berkmann18** [comment]
@tunnckoCore I've had a look at both (the latter having no documentation) and was wondering if you wanted to submit a PR with either package?

**Comment by jakebolam** [comment]
If we bring this back, it will make it difficult to support the bot in the same way (many more API requests searching and parsing files looking for the config, could actually be significant overhead)

**Comment by tunnckoCore** [comment]
@jakebolam totally agree. But we can at least support only those two - usual config and field in package.json, so not so much requests :)

**Comment by jakebolam** [comment]
How strongly are we looking to support this?

My thinking is:
- I agree, generally having an option to avoid root pollution is good
- using a key in package JSON is quickly going to blow up the package.json to many 100s, 1000s of lines (which is also bad)
- splitting the config and contributor's doesn't solve the problem of polluting the root, and actually makes it harder to understand
- I feel like there isnt a broad need for this (been open for 2.5 years with no upvotes)

**Comment by Berkmann18** [comment]
@jakebolam I think allowing the config and contributors list (which as you rightly said would be less maintainable if separated) **as long as** it doesn't exceed a certain number of contributors (e.g: 50) unless it does allow it while informing/suggesting the user that having the setting in `.all-contributorsrc` would preferable.

**Comment by tunnckoCore** [comment]
@jakebolam agree. Both are not so good. But this will be the choice of user - what he wants to pollute more.

> @Berkmann18: as long as it doesn't exceed a certain number of contributors (e.g: 50) 

That's too big too. 

But anyway.

> been open for 2.5 years with no upvotes

Yup. It's up to you and the users that use it more, I just have it in few places anyway. I'm not so strong about that :)

**Comment by Berkmann18** [comment]
> > **as long as** it doesn't exceed a certain number of contributors (e.g: 50)
> That's too big too.
50 was an exaggerated example, 20 would be personally the max I would go for that but you got the point.

**Comment by tenshiAMD** [comment]
@all-contributors/core I think this is too irrelevant today. But if anyone still wants this to be implemented. I suggest we do it by votes. Closing this for now. Thank you.
