### ISSUE TITLE
Remove trailing whitespace (flagged by popular linters)

### ISSUE THREAD

**Issue by klieret** [all-contributors/cli#340]
I am using the `trailing-whitespace` pre-commit hook. It's one of the default hooks and hence is very popular[^1].

However, the all-contributors is currently inserting trailing whitespace in the contributor table. This means that pre-commit will fail for every PR that all-contributors is opening. 

While the hook can fix this automatically with an additional commit, this behavior is still not exactly desired.

You can see the whitespace [here](https://github.com/hsf-training/hsf-training-matplotlib/pull/143/commits/d6937369a548b7f594ab2783167b49f2108efb57).

[^1]: A quick [search with sourcegraph](https://sourcegraph.com/search?q=context%3Aglobal+.pre-commit-config+content%3A%22trailing-whitespace%22+count%3A2000&patternType=standard) tells me there's more than 2k repositories use this hook.

**Comment by tenshiAMD** [comment]
@klieret @KnorpelSenf bot is now up to date. Please check. Thanks!

**Comment by klieret** [comment]
Awesome! Thanks a lot! 😃

**Comment by KnorpelSenf** [comment]
I can confirm that it works flawlessly now, thank you so much! 🎉

**Comment by tenshiAMD** [comment]
@all-contributors 
add @klieret for bug
add @KnorpelSenf for bug

**Comment by tenshiAMD** [comment]
@all-contributors
please add @klieret for bug
please add @KnorpelSenf for bug

**Comment by tenshiAMD** [comment]
@all-contributors please add @KnorpelSenf for bug. please add @klieret for bug.

**Comment by tenshiAMD** [comment]
@all-contributors please add @KnorpelSenf for bug.

**Comment by tenshiAMD** [comment]
@all-contributors please add @klieret for bug.

**Comment by tenshiAMD** [comment]
@KnorpelSenf @klieret You're welcome. Please drop a follow me to show your appreciation. Thanks! 🎉
