### ISSUE TITLE
Invalid HTML is produced if a contributor name contains quotes

### ISSUE THREAD

**Issue by dwmkerr** [all-contributors/cli#352]
**Describe the bug**

If a contributor name contains quotes, an invalid HTML table is produced, as the quotes are not properly created.

**To Reproduce**

1. Go to [github.com/dwmkerr/effective-shell](https://github.com/dwmkerr/effective-shell#contributors-)
2. Note the name of the first contributor, Xiaoyou "Elsie" Jiang (https://github.com/dwmkerr/effective-shell#contributors-)
3. Check recent builds: https://github.com/dwmkerr/effective-shell/actions/runs/4110940728/jobs/7094220872
4. Note build fails due to the error below:

``` 
15 |       <td align="center" valign="top" width="14.28%"><a href="https://github.com/xiaoyou-elsie-jiang"><img src="https://avatars.githubusercontent.com/u/101381124?v=4?s=100" width="100px;" alt="Xiaoyou "Elsie" Jiang"/><br /><sub><b>Xiaoyou "Elsie" Jiang</b></sub></a><br /><a href="https://github.com/dwmkerr/effective-shell/commits?author=xiaoyou-elsie-jiang" title="Documentation">📖</a> <a href="https://github.com/dwmkerr/effective-shell/pulls?q=is%3Apr+reviewed-by%3Axiaoyou-elsie-jiang" title="Reviewed Pull Requests">👀</a></td>
Error:  Client bundle compiled with errors therefore further build is impossible.
```

The root cause is that webpack is failing to bundle the file due to the malformatted HTML here:

```html
<img alt="Xiaoyou "Elsie" Jiang"/>
```

The quotes in the contributors name are not escaped in the HTML tag.

**Expected behavior**

Quotes in the name should be escaped in HTML img alt attrbute.

**Screenshots**

<img width="1323" alt="image" src="https://user-images.githubusercontent.com/1926984/217165094-17797215-cc3c-46d7-b046-48f3477ca293.png">

**Additional context**

The following commit in my fork demonstrates the issue by creating a failing test for a user with quotes in their name:

- https://github.com/all-contributors/cli/pull/351/commits/58fc8b5fd80fc6abd5ee52a66720d2686b45d404

The subsequent commit in the branch resolves the issue:

- https://github.com/all-contributors/cli/pull/351/commits/f602e0d926fb93e819143a6357895532ca292554

The Pull Request https://github.com/all-contributors/cli/pull/351 should resolve this issue, but should be squashed so the reproduction of the bug and the fix are in one commit!

**Comment by gr2m** [comment]
done via https://github.com/all-contributors/cli/pull/351
