### ISSUE TITLE
Adding multiple contributions partially overrides a contributor's existing ones

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [all-contributors/cli#355]
**Describe the bug**

If you add multiple `,`-separated contributions with `all-contributors add`, then only some of the new contributions may be added. It's very odd.

This does not reproduce if you only add one contribution at a time.

**To Reproduce**

See https://github.com/JoshuaKGoldberg/repros/tree/all-contributors-multiple.

```shell
git clone -b all-contributors-multiple https://github.com/JoshuaKGoldberg/repros
cd repros
npm i
```

Adding a single contribution for a contributor successfully adds them to `.all-contributorsrc`:

```shell
npx all-contributors add joshuakgoldberg content
```

```diff
"contributions": [
  "bug",
+  "content"
]
```

But, adding multiple contributions partially overrides any existing contributions:

```shell
npx all-contributors add joshuakgoldberg docs,example
```

```diff
"contributions": [
  "bug",
+  "example"
]
```

...and then running the same command again ends up with just `"example"` listed (?!):

```diff
"contributions": [
-  "bug",
+  "example"
]
```

**Expected behavior**

Adding new contributors should exclusively _add_, not take away.

**Comment by Berkmann18** [comment]
Is that happening with any particular version? I wonder if it's a regression.

**Comment by JoshuaKGoldberg** [comment]
Hmm, now I can't repro it. Also maybe it's that I was typoing and using _`docs`_? Will close - thanks!

**Comment by Berkmann18** [comment]
That's possible (especially since the bot will know what you mean but not the CLI).

**Comment by JoshuaKGoldberg** [comment]
Aha! I have a reliable reproduction of this. Filed: https://github.com/JoshuaKGoldberg/repros/tree/all-contributors-cli-adding-existing-contributions -> https://github.com/all-contributors/cli/issues/371
