### ISSUE TITLE
Breaking change: update default URL behavior

### ISSUE THREAD

**Issue by jamesplease** [all-contributors/cli#47]
:wave: Hi again!

I'm opening up this issue because [this feature](https://github.com/jfmengels/all-contributors-cli/blob/e5bd3b4c700ff91fd5b3228625a013ecf2b7cc7f/lib/generate/format-contribution-type.js#L27) seems unexpected to me. I could see someone _maybe_ adding these URLs to their projects, but it seems like that would be the exception, rather than the default.

For instance, the [all-contributors](https://github.com/kentcdodds/all-contributors) project itself doesn't include links like this. I didn't check all of the projects, but it's probably a safe bet that none of the projects listed in [the implementations list](https://github.com/kentcdodds/all-contributors/blob/master/other/IMPLEMENTATIONS.md) use these links, either.

Does anyone else think it would make more sense to default these sorts of contribution types to having no link? Right now, if most of the contributions have links that don't work, then that could possibly distract from the links that actually do point somewhere useful.

No big deal either way, but I figured I'd open this up for discussion.

Thanks for reading!

**Comment by kentcdodds** [comment]
Yeah, I've considered this. The spec actually mentions that if someone's contributed content (like a video) those links should point to their content. But it's kinda hard to automate that. Trade-offs with the amount of time we have to work on this.

If you want to change it so we only have the link for certain contribution types that'd be fine :+1:

**Comment by jmeas** [comment]
> But it's kinda hard to automate that. Trade-offs with the amount of time we have to work on this.

:+1: makes sense.

> If you want to change it so we only have the link for certain contribution types that'd be fine 👍

Cool. I'll do this sometime soon.

If anyone feels strongly _against_ this change, then that's alright, too. It can just as easily be left alone. It's a small thing, really.

**Comment by evilsoft** [comment]
Well, to second this, what if for some reason, we defaulted to no link, BUT if there is an array in the array, then the first will be the type and the second would be a url to associated.

So for instance, I could have a section of videos or tuts or something like:

```json
{
  "contributors": [
    {
      "login": "evilsoft",
      "name": "Ian Hofmann-Hicks",
      "avatar_url": "https://avatars1.githubusercontent.com/u/3665793?v=4",
      "profile": "https://github.com/evilsoft",
      "contributions": [
        "code",
        "doc",
        [ "video", "#ian-hofmannhicks-videos" ]
      ]
    }
  ]
}
```

## Videos
### Ian Hofmann-Hicks Videos

The only issue is, how the heck to specify it on the command line.

**Comment by kentcdodds** [comment]
I'd love it if we could add a linking capability and the suggestion here looks perfect :+1:

I'd be happy to accept a PR for this :+1:

**Comment by evilsoft** [comment]
if @jamesplease does not wanna grab It I would be more than happy too!!

**Comment by evilsoft** [comment]
The only thing that is questionable or raise :eye: brows will be how to specify in command line, it would be best to not have the user edit this file if they do not have to IMO.

**Comment by jamesplease** [comment]
Go for it @evilsoft !

**Comment by Berkmann18** [comment]
@evilsoft @jamesplease Friendly ping.

**Comment by tenshiAMD** [comment]
@all-contributors/core I'm looking forward to this one however I like the implementation in [this one](https://github.com/all-contributors/cli/issues/88)

**Comment by tenshiAMD** [comment]
Closing this for now. Let's move this to https://github.com/all-contributors/cli/issues/88.
